# Generated by Django 2.2 on 2019-08-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类别', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, help_text='商品类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.CreateModel(
            name='IndexCategoryAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, help_text='商品类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='goods.GoodsCategory', verbose_name='商品类别')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页类别广告',
                'verbose_name_plural': '首页类别广告',
            },
        ),
    ]
