# Generated by Django 2.2 on 2019-08-10 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_auto_20190810_1727'),
        ('trade', '0002_auto_20190415_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['-add_time'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, help_text='订单号', max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_FINISHED', '交易完成'), ('TRADE_SUCCESS', '支付成功'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSE', '交易关闭')], default='WAIT_BUYER_PAY', help_text='订单状态', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, help_text='支付交易号', max_length=100, null=True, unique=True, verbose_name='支付交易号'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'goods')},
        ),
    ]
