# Generated by Django 2.2 on 2019-05-06 23:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_auto_20190506_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'goods')},
        ),
    ]
